### ISSUE TITLE
Downloads page: links to previous versions are broken

### ISSUE THREAD

**Issue by jefscheepers** [irods/irods.org#47]
On https://irods.org/download/, links to previous versions of iRODS are listed under 'Previous versions'.
Apart from 'Source code for iRODS 3.3.1 and earlier', all links (which point to pages on https://files.irods.org/) seem to be broken. 

Just creating an issue to make you aware.
I have no need for these previous versions myself, I just stumbled into it (mistaking '4.0.3' for '4.3.0' :) )

**Comment by trel** [comment]
We've recently moved a VM from files.renci.org to files.irods.org - and updated all known links.   Everything seemed to be okay.

Can you share which file(s) you aren't able to retrieve?

**Comment by jefscheepers** [comment]
I am not able to follow the following links on that page: 

[Binaries for iRODS 4.1.x](https://files.irods.org/pub/irods/releases/)
[Plugins for iRODS 4.1.x](https://files.irods.org/pub/irods/plugins/)
[Binaries for iRODS 4.0.3](https://files.irods.org/pub/irods/releases/4.0.3/)
[iRODS 4.0.3 Manual](https://files.irods.org/pub/irods/releases/4.0.3/irods-manual-4.0.3.pdf)

Every time I get:

403 Forbidden
nginx


Important detail perhaps: I don't seem able to go to https://files.irods.org at all. 

I tested with both Edge and Chrome, on my University network and my home network.

**Comment by trel** [comment]
I've confirmed this is the case from outside the VPN - will get it corrected ASAP.

Thanks!

**Comment by trel** [comment]
https://files.irods.org should now be visible from outside the VPN.

Please confirm - thank you!

**Comment by jefscheepers** [comment]
Confirmed, I can now follow the links to the files!
Thanks, I'll close the issue.

**Comment by trel** [comment]
Excellent.
